---
- hosts: localhost
  vars_files:
    - "group_vars/{{ type }}.yml"
  roles:
    - homebrew
    - role: gantsign.oh-my-zsh
    - geerlingguy.mac.dock
    - appstore
    - role: markosamuli.pyenv
    - role: gantsign.visual-studio-code
