---
- hosts: localhost
  vars_files:
    - "group_vars/{{ type }}.yml"
  roles:
    - homebrew
    - role: gantsign.oh-my-zsh
    - role: geerlingguy.mac.dock
    - appstore
    - role: markosamuli.pyenv
    - role: gantsign.visual-studio-code
    - role: geerlingguy.dotfiles
  tasks:
    - name: Set up alias files .
      lineinfile:
        path: ~/.zshrc
        line: "source ~/{{ item }}"
      loop: "{{ zshrc_sources }}"
