---
collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
  - name: geerlingguy.mac

roles:
  - name: gantsign.oh-my-zsh
  - name: markosamuli.pyenv
  - name: gantsign.visual-studio-code
